# Generated by Django 4.2.20 on 2025-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_codename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
