# Generated by Django 4.2.20 on 2025-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_avatar_contact_avatar_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier')),
                ('warranty_period', models.CharField(blank=True, max_length=100, verbose_name='Warranty Period')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
